apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: alert-notify
build:
  artifacts:
    - image: alert-notify
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
