apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notify
  template:
    metadata:
      labels:
        app: alert-notify
    spec:
      containers:
        - name: alert-notify
          image: harbor.sangoai.com/devops/alert-notify:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: WEBHOOK_URL
              value: "https://superfan.myasustor.com:38065/hooks/55j1iuudktgcupsju8dk4hnfxr"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
